all:
  children:
    servers:
      children:
        docker-hosts:
          vars:
            ansible_user: ubuntu
            ansible_password: P@ssw0rd
            ansible_become: yes
            ansible_become_method: su
            ansible_become_user: root
            ansible_become_password: P@ssw0rd              
          hosts:
            docker-host-1:
              ansible_host: 172.16.106.129
